on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: determinatesystems/nix-installer-action@main
      - run: nix build . -o resume.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: resume.pdf
      - uses: ncipollo/release-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          allowUpdates: true
          artifacts: resume.pdf
          makeLatest: true
          tag: "latest"
          omitBody: true
          omitName: true
